ARG ruby_version=3.1.2
FROM ruby:${ruby_version}
WORKDIR /usr/src/app
RUN sed -i "s@http://\(deb\|security\).debian.org@https://mirrors.163.com@g" /etc/apt/sources.list && apt-get update -y
RUN apt install -y curl git apt-transport-https && \
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg && \
      echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" | tee /etc/apt/sources.list.d/postgresql.list && \
      apt update && \
      apt install -y postgresql-client-14
RUN bundle config mirror.https://rubygems.org https://gems.ruby-china.com && \
    bundle config set without 'development test' && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    echo 'gem: --no-document' >> ~/.gemrc && \
    cp ~/.gemrc /etc/gemrc && \
    chmod +r /etc/gemrc
