ARG TAG=1.18.1-alpine3.15
FROM ruilisi/golang:${TAG} AS build-env
RUN apk add --no-cache tzdata git make gcc musl-dev && \
    go install github.com/ruilisi/govet@v0.1.3 && \
    go install gotest.tools/gotestsum@v1.8.0 && \
    go install github.com/mgechev/revive@latest
